[project]
name = "mcp-ppt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.4.1",
    "pillow>=11.1.0",
    "python-pptx>=1.0.2",
    "pywin32>=310",
    "requests>=2.32.3",
]
